name: job-summary-to-pdf
author: Austen Stone
description: Save job summaries as a PDF files
branding:
  icon: "save"
  color: "blue"

inputs:
  name:
    description: The name of the markdown and PDF file
    default: job-summary
    required: false
  create-pdf:
    description: Whether to create a PDF file
    default: true
    required: false
  create-pdf-artifact:
    description: Whether to create an artifact with the PDF file
    default: true
    required: false
  create-md:
    description: Whether to create a markdown file
    default: true
    required: false
  create-md-artifact:
    description: Whether to create an artifact with the markdown file
    default: false
    required: false
  create-html:
    description: Whether to create an HTML file
    default: true
    required: false
  create-html-artifact:
    description: Whether to create an artifact with the HTML file
    default: false
    required: false

outputs:
  job-summary:
    description: The job summary
  job-summary-html:
    description: The job summary as HTML
  pdf-file:
    description: The path to the PDF file
  md-file:
    description: The path to the markdown file
  html-file:
    description: The path to the HTML file

runs:
  using: "node20"
  main: "dist/index.js"
